"""MaxObject stubs for gen operators. Auto-generated by gen_scraper."""
import os as _os
import sys as _sys
from maxpylang.maxobject import MaxObject

__all__ = [
    'DEGTORAD',
    'E',
    'FFTFULLSPECT',
    'FFTHOP',
    'FFTOFFSET',
    'FFTSIZE',
    'HALFPI',
    'INVPI',
    'LN10',
    'LN2',
    'LOG10E',
    'LOG2E',
    'PHI',
    'PI',
    'Param',
    'RADTODEG',
    'SAMPLERATE',
    'SQRT1_2',
    'SQRT2',
    'TWOPI',
    'VECTORSIZE',
    'abs_',
    'absdiff',
    'accum',
    'acos',
    'acosh',
    'add',
    'add_op',
    'and_',
    'and_op',
    'asin',
    'asinh',
    'atan',
    'atan2',
    'atanh',
    'atodb',
    'bool_',
    'buffer',
    'cartopol',
    'ceil',
    'cell',
    'change',
    'channels',
    'circle',
    'clamp',
    'clip',
    'concat',
    'cone',
    'constant',
    'cos',
    'cosh',
    'counter',
    'cross',
    'cycle',
    'cylinder',
    'data',
    'dbtoa',
    'dcblock',
    'degrees',
    'degtorad',
    'delay',
    'delta',
    'dim',
    'div',
    'div_op',
    'dot',
    'e',
    'elapsed',
    'eq',
    'eq_op',
    'eqp',
    'eqp_op',
    'exp',
    'exp2',
    'expr',
    'f',
    'faceforward',
    'fastcos',
    'fastexp',
    'fastpow',
    'fastsin',
    'fasttan',
    'fftfullspect',
    'ffthop',
    'fftinfo',
    'fftoffset',
    'fftsize',
    'fixdenorm',
    'fixnan',
    'float_',
    'floor',
    'fold',
    'fract',
    'ftom',
    'gate',
    'gen',
    'gt',
    'gt_op',
    'gte',
    'gte_op',
    'gtep',
    'gtep_op',
    'gtp',
    'gtp_op',
    'halfpi',
    'history',
    'hsl2rgb',
    'hypot',
    'i',
    'in_',
    'int_',
    'interp',
    'invpi',
    'isdenorm',
    'isnan',
    'latch',
    'length',
    'ln',
    'ln10',
    'ln2',
    'log',
    'log10',
    'log10e',
    'log2',
    'log2e',
    'lookup',
    'lt',
    'lt_op',
    'lte',
    'lte_op',
    'ltep',
    'ltep_op',
    'ltp',
    'ltp_op',
    'max_',
    'maximum',
    'mc_channel',
    'mc_channelcount',
    'min_',
    'minimum',
    'mix',
    'mod',
    'mod_op',
    'mstosamps',
    'mtof',
    'mul',
    'mul_op',
    'mulequals',
    'mulequals_op',
    'nearest',
    'nearestpix',
    'neg',
    'neq',
    'neq_op',
    'neqp',
    'neqp_op',
    'noise',
    'norm',
    'normalize',
    'not_',
    'not_op',
    'or_',
    'or_op',
    'out',
    'param',
    'pass_',
    'peek',
    'phasewrap',
    'phasor',
    'phi',
    'pi',
    'plane',
    'plusequals',
    'plusequals_op',
    'poke',
    'poltocar',
    'pow_',
    'qconj',
    'qmul',
    'qrot',
    'r',
    'radians',
    'radtodeg',
    'rate',
    'rdiv',
    'rdiv_op',
    'receive',
    'reflect',
    'refract',
    'rgb2hsl',
    'rmod',
    'rmod_op',
    'rotor',
    'round_',
    'rsub',
    'rsub_op',
    's',
    'sah',
    'sample',
    'samplepix',
    'samplerate',
    'sampstoms',
    'scale',
    'selector',
    'send',
    'setparam',
    'sign',
    'sin',
    'sinh',
    'slide',
    'smoothstep',
    'snorm',
    'sphere',
    'splat',
    'sqrt',
    'sqrt1_2',
    'sqrt2',
    'step',
    'sub',
    'sub_op',
    'switch',
    'switch_op',
    'swiz',
    't60',
    't60time',
    'tan',
    'tanh',
    'torus',
    'train',
    'triangle',
    'trunc',
    'twopi',
    'vec',
    'vectorsize',
    'voice',
    'voicecount',
    'wave',
    'wrap',
    'xor',
    'xor_op',
]

_NAMES = {
    'DEGTORAD': 'DEGTORAD',
    'E': 'E',
    'FFTFULLSPECT': 'FFTFULLSPECT',
    'FFTHOP': 'FFTHOP',
    'FFTOFFSET': 'FFTOFFSET',
    'FFTSIZE': 'FFTSIZE',
    'HALFPI': 'HALFPI',
    'INVPI': 'INVPI',
    'LN10': 'LN10',
    'LN2': 'LN2',
    'LOG10E': 'LOG10E',
    'LOG2E': 'LOG2E',
    'PHI': 'PHI',
    'PI': 'PI',
    'Param': 'Param',
    'RADTODEG': 'RADTODEG',
    'SAMPLERATE': 'SAMPLERATE',
    'SQRT1_2': 'SQRT1_2',
    'SQRT2': 'SQRT2',
    'TWOPI': 'TWOPI',
    'VECTORSIZE': 'VECTORSIZE',
    'abs_': 'abs',
    'absdiff': 'absdiff',
    'accum': 'accum',
    'acos': 'acos',
    'acosh': 'acosh',
    'add': 'add',
    'add_op': '+',
    'and_': 'and',
    'and_op': '&&',
    'asin': 'asin',
    'asinh': 'asinh',
    'atan': 'atan',
    'atan2': 'atan2',
    'atanh': 'atanh',
    'atodb': 'atodb',
    'bool_': 'bool',
    'buffer': 'buffer',
    'cartopol': 'cartopol',
    'ceil': 'ceil',
    'cell': 'cell',
    'change': 'change',
    'channels': 'channels',
    'circle': 'circle',
    'clamp': 'clamp',
    'clip': 'clip',
    'concat': 'concat',
    'cone': 'cone',
    'constant': 'constant',
    'cos': 'cos',
    'cosh': 'cosh',
    'counter': 'counter',
    'cross': 'cross',
    'cycle': 'cycle',
    'cylinder': 'cylinder',
    'data': 'data',
    'dbtoa': 'dbtoa',
    'dcblock': 'dcblock',
    'degrees': 'degrees',
    'degtorad': 'degtorad',
    'delay': 'delay',
    'delta': 'delta',
    'dim': 'dim',
    'div': 'div',
    'div_op': '/',
    'dot': 'dot',
    'e': 'e',
    'elapsed': 'elapsed',
    'eq': 'eq',
    'eq_op': '==',
    'eqp': 'eqp',
    'eqp_op': '==p',
    'exp': 'exp',
    'exp2': 'exp2',
    'expr': 'expr',
    'f': 'f',
    'faceforward': 'faceforward',
    'fastcos': 'fastcos',
    'fastexp': 'fastexp',
    'fastpow': 'fastpow',
    'fastsin': 'fastsin',
    'fasttan': 'fasttan',
    'fftfullspect': 'fftfullspect',
    'ffthop': 'ffthop',
    'fftinfo': 'fftinfo',
    'fftoffset': 'fftoffset',
    'fftsize': 'fftsize',
    'fixdenorm': 'fixdenorm',
    'fixnan': 'fixnan',
    'float_': 'float',
    'floor': 'floor',
    'fold': 'fold',
    'fract': 'fract',
    'ftom': 'ftom',
    'gate': 'gate',
    'gen': 'gen',
    'gt': 'gt',
    'gt_op': '>',
    'gte': 'gte',
    'gte_op': '>=',
    'gtep': 'gtep',
    'gtep_op': '>=p',
    'gtp': 'gtp',
    'gtp_op': '>p',
    'halfpi': 'halfpi',
    'history': 'history',
    'hsl2rgb': 'hsl2rgb',
    'hypot': 'hypot',
    'i': 'i',
    'in_': 'in',
    'int_': 'int',
    'interp': 'interp',
    'invpi': 'invpi',
    'isdenorm': 'isdenorm',
    'isnan': 'isnan',
    'latch': 'latch',
    'length': 'length',
    'ln': 'ln',
    'ln10': 'ln10',
    'ln2': 'ln2',
    'log': 'log',
    'log10': 'log10',
    'log10e': 'log10e',
    'log2': 'log2',
    'log2e': 'log2e',
    'lookup': 'lookup',
    'lt': 'lt',
    'lt_op': '<',
    'lte': 'lte',
    'lte_op': '<=',
    'ltep': 'ltep',
    'ltep_op': '<=p',
    'ltp': 'ltp',
    'ltp_op': '<p',
    'max_': 'max',
    'maximum': 'maximum',
    'mc_channel': 'mc_channel',
    'mc_channelcount': 'mc_channelcount',
    'min_': 'min',
    'minimum': 'minimum',
    'mix': 'mix',
    'mod': 'mod',
    'mod_op': '%',
    'mstosamps': 'mstosamps',
    'mtof': 'mtof',
    'mul': 'mul',
    'mul_op': '*',
    'mulequals': 'mulequals',
    'mulequals_op': '*=',
    'nearest': 'nearest',
    'nearestpix': 'nearestpix',
    'neg': 'neg',
    'neq': 'neq',
    'neq_op': '!=',
    'neqp': 'neqp',
    'neqp_op': '!=p',
    'noise': 'noise',
    'norm': 'norm',
    'normalize': 'normalize',
    'not_': 'not',
    'not_op': '!',
    'or_': 'or',
    'or_op': '||',
    'out': 'out',
    'param': 'param',
    'pass_': 'pass',
    'peek': 'peek',
    'phasewrap': 'phasewrap',
    'phasor': 'phasor',
    'phi': 'phi',
    'pi': 'pi',
    'plane': 'plane',
    'plusequals': 'plusequals',
    'plusequals_op': '+=',
    'poke': 'poke',
    'poltocar': 'poltocar',
    'pow_': 'pow',
    'qconj': 'qconj',
    'qmul': 'qmul',
    'qrot': 'qrot',
    'r': 'r',
    'radians': 'radians',
    'radtodeg': 'radtodeg',
    'rate': 'rate',
    'rdiv': 'rdiv',
    'rdiv_op': '!/',
    'receive': 'receive',
    'reflect': 'reflect',
    'refract': 'refract',
    'rgb2hsl': 'rgb2hsl',
    'rmod': 'rmod',
    'rmod_op': '!%',
    'rotor': 'rotor',
    'round_': 'round',
    'rsub': 'rsub',
    'rsub_op': '!-',
    's': 's',
    'sah': 'sah',
    'sample': 'sample',
    'samplepix': 'samplepix',
    'samplerate': 'samplerate',
    'sampstoms': 'sampstoms',
    'scale': 'scale',
    'selector': 'selector',
    'send': 'send',
    'setparam': 'setparam',
    'sign': 'sign',
    'sin': 'sin',
    'sinh': 'sinh',
    'slide': 'slide',
    'smoothstep': 'smoothstep',
    'snorm': 'snorm',
    'sphere': 'sphere',
    'splat': 'splat',
    'sqrt': 'sqrt',
    'sqrt1_2': 'sqrt1_2',
    'sqrt2': 'sqrt2',
    'step': 'step',
    'sub': 'sub',
    'sub_op': '-',
    'switch': 'switch',
    'switch_op': '?',
    'swiz': 'swiz',
    't60': 't60',
    't60time': 't60time',
    'tan': 'tan',
    'tanh': 'tanh',
    'torus': 'torus',
    'train': 'train',
    'triangle': 'triangle',
    'trunc': 'trunc',
    'twopi': 'twopi',
    'vec': 'vec',
    'vectorsize': 'vectorsize',
    'voice': 'voice',
    'voicecount': 'voicecount',
    'wave': 'wave',
    'wrap': 'wrap',
    'xor': 'xor',
    'xor_op': '^^',
}

_devnull = open(_os.devnull, 'w')
_old_stdout = _sys.stdout
_sys.stdout = _devnull

"""
DEGTORAD - Gen operator (Constant)
"""
DEGTORAD = MaxObject('DEGTORAD')

"""
E - Gen operator (Constant)
"""
E = MaxObject('E')

"""
FFTFULLSPECT - Gen operator (Constants)
"""
FFTFULLSPECT = MaxObject('FFTFULLSPECT')

"""
FFTHOP - Gen operator (Constants)
"""
FFTHOP = MaxObject('FFTHOP')

"""
FFTOFFSET - Gen operator (Constants)
"""
FFTOFFSET = MaxObject('FFTOFFSET')

"""
FFTSIZE - Gen operator (Constants)
"""
FFTSIZE = MaxObject('FFTSIZE')

"""
HALFPI - Gen operator (Constant)
"""
HALFPI = MaxObject('HALFPI')

"""
INVPI - Gen operator (Constant)
"""
INVPI = MaxObject('INVPI')

"""
LN10 - Gen operator (Constant)
"""
LN10 = MaxObject('LN10')

"""
LN2 - Gen operator (Constant)
"""
LN2 = MaxObject('LN2')

"""
LOG10E - Gen operator (Constant)
"""
LOG10E = MaxObject('LOG10E')

"""
LOG2E - Gen operator (Constant)
"""
LOG2E = MaxObject('LOG2E')

"""
PHI - Gen operator (Constant)
"""
PHI = MaxObject('PHI')

"""
PI - Gen operator (Constant)
"""
PI = MaxObject('PI')

"""
Param - Gen operator (Declare)
"""
Param = MaxObject('Param')

"""
RADTODEG - Gen operator (Constant)
"""
RADTODEG = MaxObject('RADTODEG')

"""
SAMPLERATE - Gen operator (Constants)
"""
SAMPLERATE = MaxObject('SAMPLERATE')

"""
SQRT1_2 - Gen operator (Constant)
"""
SQRT1_2 = MaxObject('SQRT1_2')

"""
SQRT2 - Gen operator (Constant)
"""
SQRT2 = MaxObject('SQRT2')

"""
TWOPI - Gen operator (Constant)
"""
TWOPI = MaxObject('TWOPI')

"""
VECTORSIZE - Gen operator (Constants)
"""
VECTORSIZE = MaxObject('VECTORSIZE')

"""
abs - Gen operator (Numeric)
"""
abs_ = MaxObject('abs')

"""
absdiff - Gen operator (Math)
"""
absdiff = MaxObject('absdiff')

"""
accum - Gen operator (Integrator)
"""
accum = MaxObject('accum')

"""
acos - Gen operator (Trigonometry)
"""
acos = MaxObject('acos')

"""
acosh - Gen operator (Trigonometry)
"""
acosh = MaxObject('acosh')

"""
add - Gen operator (Math)
"""
add = MaxObject('add')

"""
+ - Gen operator (Math)
"""
add_op = MaxObject('+')

"""
and - Gen operator (Logic)
"""
and_ = MaxObject('and')

"""
&& - Gen operator (Logic)
"""
and_op = MaxObject('&&')

"""
asin - Gen operator (Trigonometry)
"""
asin = MaxObject('asin')

"""
asinh - Gen operator (Trigonometry)
"""
asinh = MaxObject('asinh')

"""
atan - Gen operator (Trigonometry)
"""
atan = MaxObject('atan')

"""
atan2 - Gen operator (Trigonometry)
"""
atan2 = MaxObject('atan2')

"""
atanh - Gen operator (Trigonometry)
"""
atanh = MaxObject('atanh')

"""
atodb - Gen operator (Convert)
"""
atodb = MaxObject('atodb')

"""
bool - Gen operator (Logic)
"""
bool_ = MaxObject('bool')

"""
buffer - Gen operator (Buffer)
"""
buffer = MaxObject('buffer')

"""
cartopol - Gen operator (Math)
"""
cartopol = MaxObject('cartopol')

"""
ceil - Gen operator (Numeric)
"""
ceil = MaxObject('ceil')

"""
cell - Gen operator (Coordinate)
"""
cell = MaxObject('cell')

"""
change - Gen operator (Filter)
"""
change = MaxObject('change')

"""
channels - Gen operator (Buffer)
"""
channels = MaxObject('channels')

"""
circle - Gen operator (Surface)
"""
circle = MaxObject('circle')

"""
clamp - Gen operator (Range)
"""
clamp = MaxObject('clamp')

"""
clip - Gen operator (Range)
"""
clip = MaxObject('clip')

"""
concat - Gen operator (Vector)
"""
concat = MaxObject('concat')

"""
cone - Gen operator (Surface)
"""
cone = MaxObject('cone')

"""
constant - Gen operator (Constant)
"""
constant = MaxObject('constant')

"""
cos - Gen operator (Trigonometry)
"""
cos = MaxObject('cos')

"""
cosh - Gen operator (Trigonometry)
"""
cosh = MaxObject('cosh')

"""
counter - Gen operator (Integrator)
"""
counter = MaxObject('counter')

"""
cross - Gen operator (Vector)
"""
cross = MaxObject('cross')

"""
cycle - Gen operator (Buffer)
"""
cycle = MaxObject('cycle')

"""
cylinder - Gen operator (Surface)
"""
cylinder = MaxObject('cylinder')

"""
data - Gen operator (Buffer)
"""
data = MaxObject('data')

"""
dbtoa - Gen operator (Convert)
"""
dbtoa = MaxObject('dbtoa')

"""
dcblock - Gen operator (Filter)
"""
dcblock = MaxObject('dcblock')

"""
degrees - Gen operator (Trigonometry)
"""
degrees = MaxObject('degrees')

"""
degtorad - Gen operator (Constant)
"""
degtorad = MaxObject('degtorad')

"""
delay - Gen operator (Feedback)
"""
delay = MaxObject('delay')

"""
delta - Gen operator (Filter)
"""
delta = MaxObject('delta')

"""
dim - Gen operator (Buffer)
"""
dim = MaxObject('dim')

"""
div - Gen operator (Math)
"""
div = MaxObject('div')

"""
/ - Gen operator (Math)
"""
div_op = MaxObject('/')

"""
dot - Gen operator (Vector)
"""
dot = MaxObject('dot')

"""
e - Gen operator (Constant)
"""
e = MaxObject('e')

"""
elapsed - Gen operator (Global)
"""
elapsed = MaxObject('elapsed')

"""
eq - Gen operator (Comparison)
"""
eq = MaxObject('eq')

"""
== - Gen operator (Comparison)
"""
eq_op = MaxObject('==')

"""
eqp - Gen operator (Comparison)
"""
eqp = MaxObject('eqp')

"""
==p - Gen operator (Comparison)
"""
eqp_op = MaxObject('==p')

"""
exp - Gen operator (Powers)
"""
exp = MaxObject('exp')

"""
exp2 - Gen operator (Powers)
"""
exp2 = MaxObject('exp2')

"""
expr - Gen operator (Expression)
"""
expr = MaxObject('expr')

"""
f - Gen operator (Constant)
"""
f = MaxObject('f')

"""
faceforward - Gen operator (Vector)
"""
faceforward = MaxObject('faceforward')

"""
fastcos - Gen operator (Trigonometry)
"""
fastcos = MaxObject('fastcos')

"""
fastexp - Gen operator (Powers)
"""
fastexp = MaxObject('fastexp')

"""
fastpow - Gen operator (Powers)
"""
fastpow = MaxObject('fastpow')

"""
fastsin - Gen operator (Trigonometry)
"""
fastsin = MaxObject('fastsin')

"""
fasttan - Gen operator (Trigonometry)
"""
fasttan = MaxObject('fasttan')

"""
fftfullspect - Gen operator (Constants)
"""
fftfullspect = MaxObject('fftfullspect')

"""
ffthop - Gen operator (Constants)
"""
ffthop = MaxObject('ffthop')

"""
fftinfo - Gen operator (FFT)
"""
fftinfo = MaxObject('fftinfo')

"""
fftoffset - Gen operator (Constants)
"""
fftoffset = MaxObject('fftoffset')

"""
fftsize - Gen operator (Constants)
"""
fftsize = MaxObject('fftsize')

"""
fixdenorm - Gen operator (DSP)
"""
fixdenorm = MaxObject('fixdenorm')

"""
fixnan - Gen operator (DSP)
"""
fixnan = MaxObject('fixnan')

"""
float - Gen operator (Constant)
"""
float_ = MaxObject('float')

"""
floor - Gen operator (Numeric)
"""
floor = MaxObject('floor')

"""
fold - Gen operator (Range)
"""
fold = MaxObject('fold')

"""
fract - Gen operator (Numeric)
"""
fract = MaxObject('fract')

"""
ftom - Gen operator (Convert)
"""
ftom = MaxObject('ftom')

"""
gate - Gen operator (Route)
"""
gate = MaxObject('gate')

"""
gen - Gen operator (Subpatcher)
"""
gen = MaxObject('gen')

"""
gt - Gen operator (Comparison)
"""
gt = MaxObject('gt')

"""
> - Gen operator (Comparison)
"""
gt_op = MaxObject('>')

"""
gte - Gen operator (Comparison)
"""
gte = MaxObject('gte')

"""
>= - Gen operator (Comparison)
"""
gte_op = MaxObject('>=')

"""
gtep - Gen operator (Comparison)
"""
gtep = MaxObject('gtep')

"""
>=p - Gen operator (Comparison)
"""
gtep_op = MaxObject('>=p')

"""
gtp - Gen operator (Comparison)
"""
gtp = MaxObject('gtp')

"""
>p - Gen operator (Comparison)
"""
gtp_op = MaxObject('>p')

"""
halfpi - Gen operator (Constant)
"""
halfpi = MaxObject('halfpi')

"""
history - Gen operator (Feedback)
"""
history = MaxObject('history')

"""
hsl2rgb - Gen operator (Color)
"""
hsl2rgb = MaxObject('hsl2rgb')

"""
hypot - Gen operator (Trigonometry)
"""
hypot = MaxObject('hypot')

"""
i - Gen operator (Constant)
"""
i = MaxObject('i')

"""
in - Gen operator (Input-output)
"""
in_ = MaxObject('in')

"""
int - Gen operator (Constant)
"""
int_ = MaxObject('int')

"""
interp - Gen operator (Filter)
"""
interp = MaxObject('interp')

"""
invpi - Gen operator (Constant)
"""
invpi = MaxObject('invpi')

"""
isdenorm - Gen operator (DSP)
"""
isdenorm = MaxObject('isdenorm')

"""
isnan - Gen operator (DSP)
"""
isnan = MaxObject('isnan')

"""
latch - Gen operator (Filter)
"""
latch = MaxObject('latch')

"""
length - Gen operator (Vector)
"""
length = MaxObject('length')

"""
ln - Gen operator (Powers)
"""
ln = MaxObject('ln')

"""
ln10 - Gen operator (Constant)
"""
ln10 = MaxObject('ln10')

"""
ln2 - Gen operator (Constant)
"""
ln2 = MaxObject('ln2')

"""
log - Gen operator (Powers)
"""
log = MaxObject('log')

"""
log10 - Gen operator (Powers)
"""
log10 = MaxObject('log10')

"""
log10e - Gen operator (Constant)
"""
log10e = MaxObject('log10e')

"""
log2 - Gen operator (Powers)
"""
log2 = MaxObject('log2')

"""
log2e - Gen operator (Constant)
"""
log2e = MaxObject('log2e')

"""
lookup - Gen operator (Buffer)
"""
lookup = MaxObject('lookup')

"""
lt - Gen operator (Comparison)
"""
lt = MaxObject('lt')

"""
< - Gen operator (Comparison)
"""
lt_op = MaxObject('<')

"""
lte - Gen operator (Comparison)
"""
lte = MaxObject('lte')

"""
<= - Gen operator (Comparison)
"""
lte_op = MaxObject('<=')

"""
ltep - Gen operator (Comparison)
"""
ltep = MaxObject('ltep')

"""
<=p - Gen operator (Comparison)
"""
ltep_op = MaxObject('<=p')

"""
ltp - Gen operator (Comparison)
"""
ltp = MaxObject('ltp')

"""
<p - Gen operator (Comparison)
"""
ltp_op = MaxObject('<p')

"""
max - Gen operator (Comparison)
"""
max_ = MaxObject('max')

"""
maximum - Gen operator (Comparison)
"""
maximum = MaxObject('maximum')

"""
mc_channel - Gen operator (Global)
"""
mc_channel = MaxObject('mc_channel')

"""
mc_channelcount - Gen operator (Global)
"""
mc_channelcount = MaxObject('mc_channelcount')

"""
min - Gen operator (Comparison)
"""
min_ = MaxObject('min')

"""
minimum - Gen operator (Comparison)
"""
minimum = MaxObject('minimum')

"""
mix - Gen operator (Route)
"""
mix = MaxObject('mix')

"""
mod - Gen operator (Math)
"""
mod = MaxObject('mod')

"""
% - Gen operator (Math)
"""
mod_op = MaxObject('%')

"""
mstosamps - Gen operator (Convert)
"""
mstosamps = MaxObject('mstosamps')

"""
mtof - Gen operator (Convert)
"""
mtof = MaxObject('mtof')

"""
mul - Gen operator (Math)
"""
mul = MaxObject('mul')

"""
* - Gen operator (Math)
"""
mul_op = MaxObject('*')

"""
mulequals - Gen operator (Integrator)
"""
mulequals = MaxObject('mulequals')

"""
*= - Gen operator (Integrator)
"""
mulequals_op = MaxObject('*=')

"""
nearest - Gen operator (Buffer)
"""
nearest = MaxObject('nearest')

"""
nearestpix - Gen operator (Sampling)
"""
nearestpix = MaxObject('nearestpix')

"""
neg - Gen operator (Math)
"""
neg = MaxObject('neg')

"""
neq - Gen operator (Comparison)
"""
neq = MaxObject('neq')

"""
!= - Gen operator (Comparison)
"""
neq_op = MaxObject('!=')

"""
neqp - Gen operator (Comparison)
"""
neqp = MaxObject('neqp')

"""
!=p - Gen operator (Comparison)
"""
neqp_op = MaxObject('!=p')

"""
noise - Gen operator (Waveform)
"""
noise = MaxObject('noise')

"""
norm - Gen operator (Coordinate)
"""
norm = MaxObject('norm')

"""
normalize - Gen operator (Vector)
"""
normalize = MaxObject('normalize')

"""
not - Gen operator (Logic)
"""
not_ = MaxObject('not')

"""
! - Gen operator (Logic)
"""
not_op = MaxObject('!')

"""
or - Gen operator (Logic)
"""
or_ = MaxObject('or')

"""
|| - Gen operator (Logic)
"""
or_op = MaxObject('||')

"""
out - Gen operator (Input-output)
"""
out = MaxObject('out')

"""
param - Gen operator (Declare)
"""
param = MaxObject('param')

"""
pass - Gen operator (Ignore)
"""
pass_ = MaxObject('pass')

"""
peek - Gen operator (Buffer)
"""
peek = MaxObject('peek')

"""
phasewrap - Gen operator (Filter)
"""
phasewrap = MaxObject('phasewrap')

"""
phasor - Gen operator (Waveform)
"""
phasor = MaxObject('phasor')

"""
phi - Gen operator (Constant)
"""
phi = MaxObject('phi')

"""
pi - Gen operator (Constant)
"""
pi = MaxObject('pi')

"""
plane - Gen operator (Surface)
"""
plane = MaxObject('plane')

"""
plusequals - Gen operator (Integrator)
"""
plusequals = MaxObject('plusequals')

"""
+= - Gen operator (Integrator)
"""
plusequals_op = MaxObject('+=')

"""
poke - Gen operator (Buffer)
"""
poke = MaxObject('poke')

"""
poltocar - Gen operator (Math)
"""
poltocar = MaxObject('poltocar')

"""
pow - Gen operator (Powers)
"""
pow_ = MaxObject('pow')

"""
qconj - Gen operator (Quaternion)
"""
qconj = MaxObject('qconj')

"""
qmul - Gen operator (Quaternion)
"""
qmul = MaxObject('qmul')

"""
qrot - Gen operator (Quaternion)
"""
qrot = MaxObject('qrot')

"""
r - Gen operator (Route)
"""
r = MaxObject('r')

"""
radians - Gen operator (Trigonometry)
"""
radians = MaxObject('radians')

"""
radtodeg - Gen operator (Constant)
"""
radtodeg = MaxObject('radtodeg')

"""
rate - Gen operator (Waveform)
"""
rate = MaxObject('rate')

"""
rdiv - Gen operator (Math)
"""
rdiv = MaxObject('rdiv')

"""
!/ - Gen operator (Math)
"""
rdiv_op = MaxObject('!/')

"""
receive - Gen operator (Route)
"""
receive = MaxObject('receive')

"""
reflect - Gen operator (Vector)
"""
reflect = MaxObject('reflect')

"""
refract - Gen operator (Vector)
"""
refract = MaxObject('refract')

"""
rgb2hsl - Gen operator (Color)
"""
rgb2hsl = MaxObject('rgb2hsl')

"""
rmod - Gen operator (Math)
"""
rmod = MaxObject('rmod')

"""
!% - Gen operator (Math)
"""
rmod_op = MaxObject('!%')

"""
rotor - Gen operator (Vector)
"""
rotor = MaxObject('rotor')

"""
round - Gen operator (Numeric)
"""
round_ = MaxObject('round')

"""
rsub - Gen operator (Math)
"""
rsub = MaxObject('rsub')

"""
!- - Gen operator (Math)
"""
rsub_op = MaxObject('!-')

"""
s - Gen operator (Route)
"""
s = MaxObject('s')

"""
sah - Gen operator (Filter)
"""
sah = MaxObject('sah')

"""
sample - Gen operator (Buffer)
"""
sample = MaxObject('sample')

"""
samplepix - Gen operator (Sampling)
"""
samplepix = MaxObject('samplepix')

"""
samplerate - Gen operator (Constants)
"""
samplerate = MaxObject('samplerate')

"""
sampstoms - Gen operator (Convert)
"""
sampstoms = MaxObject('sampstoms')

"""
scale - Gen operator (Range)
"""
scale = MaxObject('scale')

"""
selector - Gen operator (Route)
"""
selector = MaxObject('selector')

"""
send - Gen operator (Route)
"""
send = MaxObject('send')

"""
setparam - Gen operator (Subpatcher)
"""
setparam = MaxObject('setparam')

"""
sign - Gen operator (Numeric)
"""
sign = MaxObject('sign')

"""
sin - Gen operator (Trigonometry)
"""
sin = MaxObject('sin')

"""
sinh - Gen operator (Trigonometry)
"""
sinh = MaxObject('sinh')

"""
slide - Gen operator (Filter)
"""
slide = MaxObject('slide')

"""
smoothstep - Gen operator (Route)
"""
smoothstep = MaxObject('smoothstep')

"""
snorm - Gen operator (Coordinate)
"""
snorm = MaxObject('snorm')

"""
sphere - Gen operator (Surface)
"""
sphere = MaxObject('sphere')

"""
splat - Gen operator (Buffer)
"""
splat = MaxObject('splat')

"""
sqrt - Gen operator (Powers)
"""
sqrt = MaxObject('sqrt')

"""
sqrt1_2 - Gen operator (Constant)
"""
sqrt1_2 = MaxObject('sqrt1_2')

"""
sqrt2 - Gen operator (Constant)
"""
sqrt2 = MaxObject('sqrt2')

"""
step - Gen operator (Comparison)
"""
step = MaxObject('step')

"""
sub - Gen operator (Math)
"""
sub = MaxObject('sub')

"""
- - Gen operator (Math)
"""
sub_op = MaxObject('-')

"""
switch - Gen operator (Route)
"""
switch = MaxObject('switch')

"""
? - Gen operator (Route)
"""
switch_op = MaxObject('?')

"""
swiz - Gen operator (Vector)
"""
swiz = MaxObject('swiz')

"""
t60 - Gen operator (DSP)
"""
t60 = MaxObject('t60')

"""
t60time - Gen operator (DSP)
"""
t60time = MaxObject('t60time')

"""
tan - Gen operator (Trigonometry)
"""
tan = MaxObject('tan')

"""
tanh - Gen operator (Trigonometry)
"""
tanh = MaxObject('tanh')

"""
torus - Gen operator (Surface)
"""
torus = MaxObject('torus')

"""
train - Gen operator (Waveform)
"""
train = MaxObject('train')

"""
triangle - Gen operator (Waveform)
"""
triangle = MaxObject('triangle')

"""
trunc - Gen operator (Numeric)
"""
trunc = MaxObject('trunc')

"""
twopi - Gen operator (Constant)
"""
twopi = MaxObject('twopi')

"""
vec - Gen operator (Vector)
"""
vec = MaxObject('vec')

"""
vectorsize - Gen operator (Constants)
"""
vectorsize = MaxObject('vectorsize')

"""
voice - Gen operator (Global)
"""
voice = MaxObject('voice')

"""
voicecount - Gen operator (Global)
"""
voicecount = MaxObject('voicecount')

"""
wave - Gen operator (Buffer)
"""
wave = MaxObject('wave')

"""
wrap - Gen operator (Range)
"""
wrap = MaxObject('wrap')

"""
xor - Gen operator (Logic)
"""
xor = MaxObject('xor')

"""
^^ - Gen operator (Logic)
"""
xor_op = MaxObject('^^')

_sys.stdout = _old_stdout
_devnull.close()
del _devnull, _old_stdout
